import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

export const studentStyles = StyleSheet.create({
  header: {
    backgroundColor: '#4a80f5',
  },
  contentContainer: {
    flex: 1,
  },
  mapContainer: {
    height: 250,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  map: {
    width: Dimensions.get('window').width,
    height: 250,
  },
  webMapPlaceholder: {
    width: Dimensions.get('window').width,
    height: 250,
    backgroundColor: '#e8eaed',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  webMapIconsContainer: {
    flexDirection: 'row',
    marginTop: 15,
    marginBottom: 15,
    justifyContent: 'space-around',
    width: '80%',
  },
  webMapIcon: {
    alignItems: 'center',
  },
  webMapIconLabel: {
    marginTop: 5,
    fontSize: 12,
    color: '#555',
  },
  webMapNote: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    marginTop: 10,
  },
  mapPlaceholder: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#666',
  },
  mapOverlay: {
    position: 'absolute',
    bottom: 20,
    right: 20,
  },
  sosButton: {
    backgroundColor: '#ff3b30',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  sosButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  userMarker: {
    backgroundColor: '#4a80f5',
    padding: 5,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'white',
  },
  shuttleMarker: {
    backgroundColor: '#ff9500',
    padding: 5,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'white',
  },
  collegeMarker: {
    backgroundColor: '#34c759',
    padding: 5,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'white',
  },
  sectionContainer: {
    padding: 15,
    backgroundColor: 'white',
    marginVertical: 10,
    borderRadius: 10,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#333',
  },
  infoText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
  },
  busCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  busInfo: {
    flex: 3,
  },
  busName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
  },
  busRoute: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  busEta: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  etaText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4a80f5',
  },
  confirmButton: {
    backgroundColor: '#4a80f5',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  confirmButtonText: {
    color: 'white',
    fontSize: 12,
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  actionButton: {
    alignItems: 'center',
    padding: 10,
  },
  actionText: {
    marginTop: 5,
    fontSize: 12,
    color: '#333',
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingVertical: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 5,
  },
  activeNavItem: {
    borderTopWidth: 3,
    borderTopColor: '#4a80f5',
    paddingTop: 2,
  },
  navText: {
    fontSize: 12,
    color: '#888',
    marginTop: 4,
  },
  activeNavText: {
    color: '#4a80f5',
  },
  trackingCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 15,
    padding: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#ff9500',
  },
  trackingCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  busIconContainer: {
    marginRight: 10,
  },
  trackingCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    flex: 1,
  },
  trackingCardEta: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4a80f5',
  },
  trackingCardDetails: {
    marginTop: 10,
  },
  trackingCardRoute: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  trackingMetrics: {
    flexDirection: 'row',
    marginTop: 5,
  },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  metricText: {
    fontSize: 12,
    color: '#666',
    marginLeft: 5,
  },
  scheduleCard: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
  },
  scheduleCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  scheduleCardRoute: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
  },
  scheduleStop: {
    flexDirection: 'row',
    borderLeftWidth: 1,
    borderLeftColor: '#4a80f5',
    paddingLeft: 15,
    paddingVertical: 8,
  },
  scheduleTime: {
    width: 70,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  scheduleLocation: {
    fontSize: 14,
    color: '#666',
  },
  profileSection: {
    backgroundColor: '#fff',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4a80f5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  profileId: {
    fontSize: 14,
    color: '#666',
  },
  settingSection: {
    marginTop: 10,
  },
  settingSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  settingLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingLabel: {
    fontSize: 16,
    color: '#333',
    marginLeft: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 10,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  modalBody: {
    padding: 15,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
  },
  locationSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
  },
  locationText: {
    fontSize: 14,
    color: '#333',
  },
  alertNote: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  cancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: '#f1f1f1',
  },
  cancelButtonText: {
    fontSize: 14,
    color: '#333',
  },
  sosModalButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: '#ff3b30',
  },
  sosModalButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  confirmModalButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: '#4a80f5',
  },
  confirmModalButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  attendanceInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  busIconLarge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ff9500',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  attendanceDetails: {
    flex: 1,
  },
  attendanceBusName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  attendanceRoute: {
    fontSize: 14,
    color: '#666',
  },
  attendanceEta: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4a80f5',
    marginTop: 5,
  },
  attendanceNote: {
    fontSize: 14,
    color: '#666',
    marginVertical: 10,
  },
});