// Shuttle model - represents a physical shuttle vehicle
export const ShuttleModel = {
  id: '',                  // Generated by Firebase
  name: '',                // Display name (e.g., "Shuttle A")
  driverId: '',            // Reference to the driver
  routeId: '',             // Current assigned route
  capacity: 0,             // Maximum passenger capacity
  location: {              // Current GPS coordinates
    latitude: 0,
    longitude: 0
  },
  status: '',              // 'active', 'inactive', 'maintenance'
  lastUpdated: null        // Timestamp of last location update
};

// Bus model - represents the campus bus
export const BusModel = {
  id: '',                  // Generated by Firebase
  name: '',                // Display name (e.g., "Campus Bus")
  driverId: '',            // Reference to the driver
  routeId: '',             // Reference to the route
  capacity: 0,             // Maximum passenger capacity
  location: {              // Current GPS coordinates
    latitude: 0,
    longitude: 0
  },
  status: '',              // 'active', 'inactive', 'maintenance'
  lastUpdated: null,       // Timestamp of last location update
  eta: ''                  // Estimated time of arrival
};

// Route model - represents a predefined shuttle route
export const RouteModel = {
  id: '',                  // Generated by Firebase
  name: '',                // Display name (e.g., "Route A")
  description: '',         // Description of the route
  stops: [                 // Array of stops along the route
    {
      name: '',            // Name of the stop
      address: '',         // Address of the stop
      location: {          // GPS coordinates
        latitude: 0,
        longitude: 0
      },
      scheduledTime: ''    // Scheduled arrival time
    }
  ],
  coordinates: [           // Array of coordinates to draw the route
    {
      latitude: 0,
      longitude: 0
    }
  ],
  estimatedDuration: 0     // Estimated duration in minutes
};

// Route model - represents the campus route
export const RouteModel = {
  id: '',                  // Generated by Firebase
  name: '',                // Display name (e.g., "Campus Route")
  description: '',         // Description of the route
  stops: [                 // Array of stops along the route
    {
      name: '',            // Name of the stop
      address: '',         // Address of the stop
      location: {          // GPS coordinates
        latitude: 0,
        longitude: 0
      },
      scheduledTime: '',   // Scheduled arrival time
      students: 0          // Number of students at this stop
    }
  ],
  coordinates: [           // Array of coordinates to draw the route
    {
      latitude: 0,
      longitude: 0
    }
  ],
  estimatedDuration: 0     // Estimated duration in minutes
};

// Student model - represents a registered student
export const StudentModel = {
  id: '',                  // Generated by Firebase
  studentId: '',           // University ID
  name: '',                // Student name
  email: '',               // Student email
  phoneNumber: '',         // Contact number
  preferredPickupLocation: ''  // Favorite/common pickup location
};

// Attendance model - tracks student attendance
export const AttendanceModel = {
  id: '',                  // Generated by Firebase
  studentId: '',           // Reference to student
  busId: '',               // Reference to bus
  pickupLocation: '',      // Where they'll be picked up
  status: '',              // 'confirmed', 'boarded', 'cancelled'
  timestamp: null,         // When they confirmed
  boardedTimestamp: null,  // When they actually boarded (optional)
  displayName: '',         // Student display name
  createdAt: ''            // ISO date string for easier reading
};

// Driver model - represents a shuttle driver
export const DriverModel = {
  id: '',                  // Generated by Firebase
  name: '',                // Driver name
  employeeId: '',          // University/Company ID
  phoneNumber: '',         // Contact number
  assignedShuttleId: '',   // Current assigned shuttle
  status: ''               // 'on-duty', 'off-duty'
};

// Driver model - represents the bus driver
export const DriverModel = {
  id: '',                  // Generated by Firebase
  name: '',                // Driver name
  employeeId: '',          // University/Company ID
  phoneNumber: '',         // Contact number
  status: ''               // 'on-duty', 'off-duty'
};